import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WorkflowDemo from "@/components/WorkflowDemo";
import { LeadCaptureVisual } from "@/components/LeadCapture";
import { PRIMARY_PHONE_DISPLAY, PRIMARY_PHONE_HREF } from "@/app/components/cta";
export default function DemoPage() {
 return <div className="min-h-screen bg-background text-foreground"><Navbar /><main><section className="container mx-auto px-6 pb-14 pt-32 sm:pt-40"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Demos & examples</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-bold leading-tight sm:text-5xl">See the handoff. Try the workflow.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Explore how lead capture starts a conversation and how custom software helps your team follow through. Examples are labeled; they are not client case studies.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#workflow-demo" className="inline-flex min-h-12 items-center rounded-full bg-orange-700 px-6 font-semibold text-primary-foreground">Try the dashboard</a><a href="#lead-demo" className="inline-flex min-h-12 items-center rounded-full border border-white/20 px-6 font-semibold">See text back</a></div></section>
 <WorkflowDemo />
 <section id="lead-demo" className="scroll-mt-28 bg-zinc-950 py-16 text-white"><div className="container mx-auto grid items-center gap-10 px-6 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-300">Lead capture & response</p><h2 className="mt-4 font-display text-3xl font-bold">Turn a missed call into a conversation.</h2><p className="mt-5 leading-relaxed text-zinc-300">A text-back flow gives eligible missed callers a way to reply. Your team can then review the request and follow up. It is different from an AI receptionist, which answers the call itself.</p><p className="mt-4 text-sm leading-relaxed text-zinc-300">Want to try it with your own phone? Call to arrange a missed-call text-back demonstration on our business line. This is not an AI voice demo. Mobile eligibility, opt-outs and carrier delivery affect whether a text arrives.</p><a href={PRIMARY_PHONE_HREF} data-track-event="demo_phone_click" data-track-lane="lead-capture" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-orange-700 px-6 font-semibold text-white">Call {PRIMARY_PHONE_DISPLAY}</a><div className="mt-5 flex flex-wrap gap-5 text-sm font-semibold text-orange-300"><Link href="/missed-call-text-back" className="py-2 underline">Missed-call text back</Link><Link href="/ai-employees/ai-receptionist" className="py-2 underline">AI receptionist</Link></div></div><LeadCaptureVisual /></div></section>
 <section className="container mx-auto px-6 py-16 text-center"><h2 className="font-display text-3xl font-bold">What would this look like in your business?</h2><p className="mx-auto mt-4 max-w-2xl leading-relaxed text-muted-foreground">We start with your actual tools, handoffs and limits. Scope, access and success criteria come before a build.</p><Link href="/contact?source=demo" data-track-event="cta_click" data-track-source="demo" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-orange-700 px-7 font-semibold text-primary-foreground">Discuss your setup</Link></section>
 </main><Footer /></div>;
}
