import Link from "next/link";
import Image from "next/image";
import { PRIMARY_PHONE_DISPLAY, PRIMARY_PHONE_HREF } from "@/app/components/cta";
import { SITE_LOGO_ALT, SITE_LOGO_INTRINSIC, SITE_LOGO_PATH, siteLogoFooterImageClassName } from "@/lib/siteLogo";
const columns = [
  { title: "Lead capture", links: [["Missed-call text back", "/missed-call-text-back"], ["AI receptionist", "/ai-employees/ai-receptionist"], ["Lead response & follow-up", "/ai-lead-response-system"], ["Missed-call calculator", "/missed-call-calculator"]] },
  { title: "Custom software & AI", links: [["Workflow automation", "/workflow-automation-consultant"], ["Custom dashboards", "/custom-business-dashboard"], ["Internal tools", "/internal-tools-for-small-business"], ["AI agents", "/ai-agents-for-business"]] },
  { title: "Explore", links: [["Services", "/services"], ["Demos & examples", "/demo"], ["Practical guides", "/articles"], ["About Brendan", "/about"], ["Contact", "/contact"]] },
];
export default function Footer() {
 return <footer className="border-t border-zinc-800 bg-zinc-950 py-12 text-zinc-300"><div className="container mx-auto px-5 sm:px-6"><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><Link href="/" className="inline-flex rounded-lg bg-black px-2 py-1.5"><Image src={SITE_LOGO_PATH} alt={SITE_LOGO_ALT} width={SITE_LOGO_INTRINSIC.width} height={SITE_LOGO_INTRINSIC.height} className={siteLogoFooterImageClassName} /></Link><p className="mt-4 max-w-sm text-sm leading-relaxed">Lead capture that keeps conversations moving. Custom software and AI that make the work easier.</p><a href={PRIMARY_PHONE_HREF} data-track-event="phone_click" data-track-source="footer" className="mt-3 inline-flex min-h-11 items-center font-semibold text-orange-300 hover:underline">{PRIMARY_PHONE_DISPLAY}</a></div>{columns.map(column => <div key={column.title}><h2 className="font-semibold text-white">{column.title}</h2><ul className="mt-3 space-y-1">{column.links.map(([label,href]) => <li key={href}><Link href={href} className="inline-flex min-h-11 items-center text-sm hover:text-orange-300 hover:underline">{label}</Link></li>)}</ul></div>)}</div><div className="mt-8 flex flex-col gap-4 border-t border-zinc-800 pt-6 text-xs sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} 247ROI. All rights reserved.</p><div className="flex flex-wrap gap-6"><Link href="/privacy-policy" className="py-2 hover:underline">Privacy Policy</Link><Link href="/terms-of-service" className="py-2 hover:underline">Terms of Service</Link></div></div></div></footer>;
}
