import Link from "next/link";
import { ArrowRight, Check, Phone } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { LeadCaptureVisual, MISSED_CALL_PATH, RECEPTIONIST_PATH, offerButton, offerContact, type LeadOffer } from "@/components/LeadCapture";
import { PRIMARY_PHONE_DISPLAY, PRIMARY_PHONE_HREF } from "@/app/components/cta";

const missedFaq = [
  ["Is this an AI receptionist?", "No. Text back starts an SMS conversation after an eligible missed call. An AI receptionist answers the call itself. You can start with text back without adding voice AI."],
  ["Can I keep my business number?", "We first check your number, carrier and current phone setup. Keeping the number may be possible through a compatible connection or forwarding arrangement; we confirm before you commit."],
  ["Does it automatically book jobs?", "Basic text back opens the conversation. Your team still handles replies and confirms the next step. Qualification, CRM updates or booking can be scoped separately when useful."],
  ["Will every missed caller receive a text?", "No. Delivery depends on the caller’s number, messaging eligibility, carrier filtering and your configuration. Landlines, blocked numbers and opted-out contacts may not receive messages."],
  ["What about consent and opt-outs?", "Setup must address applicable messaging consent, sender registration and opt-out handling. A missed call is not blanket permission for ongoing promotional texts. We define the permitted message flow before launch."],
  ["What does it cost?", "We confirm setup, expected message volume, included usage, monthly pricing and any introductory terms before you commit. Ask us for a clear quote based on your setup and expected usage."],
];
const voiceFaq = [
  ["Does it replace my team?", "It can handle overflow or after-hours calls while people stay in charge of exceptions and sensitive decisions. We agree on when the AI answers and when a person takes over."],
  ["Can it schedule appointments?", "Where the calendar and booking rules support it, scheduling can be part of the setup. Otherwise it captures the request for your team to confirm. We do not promise integrations before checking them."],
  ["What happens with urgent or unusual calls?", "We define escalation rules, fallback contacts and what to do if a transfer cannot connect. It is not an emergency-response service and should not make sensitive decisions on its own."],
  ["Will callers know they are talking to AI?", "The greeting can identify it as a virtual receptionist. We agree on disclosure, any recording notice, data handling and applicable requirements as part of setup."],
  ["Can I start with text back instead?", "Yes. If your main problem is missed calls and you can manage replies, missed-call text back is a simpler starting point. You do not have to buy both."],
];

export default function LeadOfferPage({ offer }: { offer: LeadOffer }) {
  const voice = offer === "ai-receptionist";
  const title = voice ? "AI receptionist" : "Missed-call text back";
  const steps = voice ? [
    ["Set the answering rules", "Choose overflow, after-hours or another defined call flow. Set the questions, boundaries and handoff contacts."],
    ["Give callers a useful next step", "Answer common questions, gather the details you need and route or request bookings within agreed rules."],
    ["Keep your team in the loop", "Review call summaries and exceptions. Confirm what needs a human and improve the flow using real calls."],
  ] : [
    ["A customer calls. You’re busy.", "You’re on a job, helping another customer or away from the phone. The call goes unanswered."],
    ["A helpful text goes out", "For eligible missed calls, your configured message offers a simple way to reply instead of waiting on voicemail."],
    ["Your team picks up the conversation", "See what the caller needs and follow up with a clear next step. No automatic booking promise or forced upsell."],
  ];
  const features = voice ? ["A greeting built around your business", "Answers based on agreed business information", "Contact details and reason for calling", "Defined transfers and fallback rules", "Call summaries for follow-up", "Human control over exceptions"] : ["A message written for your business", "Defined missed-call triggers and timing", "A clear way for callers to reply", "A designated owner for follow-up", "Duplicate-message and opt-out rules", "A setup check before going live"];
  return <div className="min-h-screen bg-zinc-50 text-zinc-950"><Navbar /><main>
    <section className="relative overflow-hidden bg-zinc-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(234,88,12,0.18),transparent_65%)]" /><div className="container relative mx-auto grid gap-10 px-5 pb-16 pt-28 sm:px-6 sm:pt-36 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:gap-16">
      <div><Link href="/services" className="text-sm font-semibold text-orange-300 hover:underline">Lead capture / {title}</Link>
        <h1 className="mt-5 font-display text-4xl font-bold leading-[1.08] sm:text-5xl lg:text-6xl">{voice ? "Your next customer shouldn’t have to wait for you to pick up." : "Miss the call. Not the chance to win the customer."}</h1>
        <p className="mt-6 max-w-xl text-lg leading-relaxed text-zinc-300">{voice ? "An AI receptionist that answers within your rules, captures what callers need, and gives your team a clearer next step—even when you’re tied up." : "Give missed callers a prompt, helpful text and an easy way to reply. Stay in the conversation while you’re busy running the business."}</p>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link href={offerContact(offer)} className={offerButton} data-track-event="cta_click" data-track-label={`${offer}_hero_inquiry`} data-track-source={offer}>{voice ? "Discuss AI answering" : "Check my phone setup"}<ArrowRight className="h-4 w-4" aria-hidden /></Link><a href="#how-it-works" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 px-6 py-3 text-sm font-semibold hover:bg-white/10">See how it works</a></div>
        <p className="mt-4 text-sm text-zinc-400">Start with one call flow. Expand only if it makes sense.</p>
      </div><LeadCaptureVisual voice={voice} />
    </div></section>
    {!voice && <section className="border-b border-zinc-200 bg-white py-8"><div className="container mx-auto px-5 sm:px-6"><h2 className="font-display text-xl font-bold">See text back on a real phone.</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-zinc-600">Call <a href={PRIMARY_PHONE_HREF} data-track-event="demo_phone_click" data-track-lane="lead-capture" className="font-semibold text-orange-700 underline">{PRIMARY_PHONE_DISPLAY}</a> to arrange a text-back demonstration on our business line. This is not an AI voice demo; delivery depends on mobile eligibility, carrier support and opt-out status.</p><Link href="/articles/missed-call-text-back-vs-ai-receptionist" className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-orange-700 underline">Compare text back and AI answering</Link></div></section>}
    <section id="how-it-works" className="scroll-mt-28 py-16 sm:py-20"><div className="container mx-auto px-5 sm:px-6"><p className="text-xs font-bold uppercase tracking-widest text-orange-700">The handoff, made simple</p><h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">{voice ? "From ringing phone to useful next step." : "Three steps. One less missed opportunity."}</h2><div className="mt-9 grid gap-6 md:grid-cols-3">{steps.map(([heading,body],i)=><div key={heading} className="rounded-2xl border border-zinc-200 bg-white p-6"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-100 font-bold text-orange-800">{i+1}</span><h3 className="mt-5 text-xl font-bold">{heading}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{body}</p></div>)}</div></div></section>
    <section className="border-y border-zinc-200 bg-white py-16"><div className="container mx-auto grid gap-10 px-5 sm:px-6 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-700">Designed around your business</p><h2 className="mt-3 font-display text-3xl font-bold">Useful on day one. Clear about its limits.</h2><p className="mt-5 max-w-xl leading-relaxed text-zinc-600">{voice ? "The goal isn’t a voice that can say anything. It’s a dependable call flow with useful information, defined boundaries and a person to handle the exceptions." : "You don’t need a full software overhaul to respond sooner. Start with the missed-call gap and a reliable way for your team to handle the replies."}</p></div><ul className="grid gap-4 sm:grid-cols-2">{features.map(feature=><li key={feature} className="flex items-start gap-3 rounded-xl bg-zinc-50 p-4 text-sm font-medium"><Check className="h-5 w-5 shrink-0 text-orange-600" aria-hidden />{feature}</li>)}</ul></div></section>
    <section className="py-16"><div className="container mx-auto grid gap-6 px-5 sm:px-6 lg:grid-cols-2"><div className="rounded-2xl bg-zinc-900 p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-300">Choose the right starting point</p><h2 className="mt-3 font-display text-2xl font-bold">{voice ? "Just need a safety net for missed calls?" : "Need someone to answer, not just text back?"}</h2><p className="mt-4 text-sm leading-relaxed text-zinc-300">{voice ? "Text back is a simpler fit when your team can handle the conversation once the caller replies." : "An AI receptionist can handle the conversation on the phone, collect details and follow your routing rules."}</p><Link href={voice ? MISSED_CALL_PATH : RECEPTIONIST_PATH} className="mt-6 inline-flex min-h-11 items-center gap-2 font-semibold text-orange-300 hover:underline">{voice ? "Compare missed-call text back" : "Explore AI receptionist"}<ArrowRight className="h-4 w-4" aria-hidden /></Link></div><div className="rounded-2xl border border-zinc-200 bg-white p-7"><p className="text-xs font-bold uppercase tracking-widest text-orange-700">Beyond the first response</p><h2 className="mt-3 font-display text-2xl font-bold">Connect the follow-through.</h2><p className="mt-4 text-sm leading-relaxed text-zinc-600">When the time is right, connect lead capture to your CRM, follow-up workflows and custom dashboards. Keep inquiries visible instead of scattered across phones, inboxes and spreadsheets.</p><Link href="/services" className="mt-6 inline-flex min-h-11 items-center gap-2 font-semibold text-orange-700 hover:underline">See custom business systems<ArrowRight className="h-4 w-4" aria-hidden /></Link></div></div></section>
    <section id="offer" className="scroll-mt-28 bg-orange-50 py-16"><div className="container mx-auto max-w-4xl px-5 text-center sm:px-6"><p className="text-xs font-bold uppercase tracking-widest text-orange-800">Start with the calls you already get</p><h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">Let’s check what fits your business.</h2><p className="mx-auto mt-5 max-w-2xl leading-relaxed text-zinc-700">Tell us how your phone is set up and what happens when you can’t answer. We’ll discuss a practical starting point, usage and pricing before you commit.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href={offerContact(offer)} className={offerButton} data-track-event="cta_click" data-track-label={`${offer}_setup_inquiry`} data-track-source={offer}>Discuss my setup<ArrowRight className="h-4 w-4" aria-hidden /></Link><a href={PRIMARY_PHONE_HREF} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-zinc-300 px-6 py-3 text-sm font-bold text-zinc-900 hover:bg-white" data-track-event="phone_click" data-track-source={offer}><Phone className="h-4 w-4" aria-hidden />{PRIMARY_PHONE_DISPLAY}</a></div><p className="mt-4 text-xs text-zinc-600">No checkout or payment required to discuss your options.</p></div></section>
    <section className="py-16 sm:py-20"><div className="container mx-auto max-w-4xl px-5 sm:px-6"><h2 className="font-display text-3xl font-bold">A few things worth knowing.</h2><div className="mt-7 divide-y divide-zinc-200">{(voice ? voiceFaq : missedFaq).map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer py-1 pr-4 text-base font-semibold focus-visible:outline-orange-600">{q}</summary><p className="mt-3 max-w-3xl text-sm leading-relaxed text-zinc-600">{a}</p></details>)}</div></div></section>
  </main><Footer /></div>;
}
