import Link from "next/link";
import { ArrowRight, MessageSquare, PanelsTopLeft } from "lucide-react";
export default function ServicePaths() {
  const lanes = [
    { id: "lead-capture", title: "Lead capture & response", icon: MessageSquare, text: "Respond sooner when you’re busy. Give callers and new inquiries a clear next step instead of letting them go cold.", links: [["Missed-call text back", "/missed-call-text-back"], ["AI receptionist", "/ai-employees/ai-receptionist"], ["Lead response & follow-up", "/ai-lead-response-system"]], cta: "Discuss lead capture" },
    { id: "custom-software", title: "Custom software & AI", icon: PanelsTopLeft, text: "Reduce repetitive admin work and see what needs attention. Build around your existing tools, processes and approval rules.", links: [["Automated workflows", "/workflow-automation-consultant"], ["Custom dashboards", "/custom-business-dashboard"], ["Internal tools & AI agents", "/internal-tools-for-small-business"]], cta: "Discuss a custom system" },
  ];
  return <section id="service-paths" className="scroll-mt-24 border-b border-zinc-200 bg-zinc-50 py-16 text-zinc-950 sm:py-20"><div className="container mx-auto px-5 sm:px-6"><p className="text-xs font-bold uppercase tracking-widest text-orange-700">Two ways we help</p><h2 className="mt-3 max-w-3xl font-display text-3xl font-bold sm:text-4xl">Capture the opportunity. Improve the work.</h2>
    <div className="mt-8 grid gap-6 md:grid-cols-2">{lanes.map(lane => {const Icon=lane.icon; return <article id={lane.id} key={lane.id} className="flex scroll-mt-24 flex-col rounded-2xl border border-zinc-200 bg-white p-6 sm:p-8"><Icon className="h-7 w-7 text-orange-700" aria-hidden /><h3 className="mt-5 font-display text-2xl font-bold">{lane.title}</h3><p className="mt-4 text-sm leading-relaxed text-zinc-600">{lane.text}</p><ul className="my-6 flex-1 space-y-2">{lane.links.map(([label,href]) => <li key={href}><Link href={href} data-track-event="service_interest" data-track-lane={lane.id} className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-zinc-900 underline decoration-zinc-300 underline-offset-4 hover:text-orange-700">{label}<ArrowRight className="h-4 w-4" aria-hidden /></Link></li>)}</ul><Link href={`/contact?offer=${lane.id}&source=service-paths`} data-track-event="cta_click" data-track-lane={lane.id} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-orange-700 px-5 py-3 text-center text-sm font-bold text-white hover:bg-orange-800">{lane.cta}<ArrowRight className="h-4 w-4" aria-hidden /></Link></article>;})}</div>
  </div></section>;
}
