import assert from 'node:assert/strict';
import {readFileSync, writeFileSync} from 'node:fs';
import {pageSpeedDeficits} from '../src/lib/audit/probes/pagespeed';
import {measurementCoverage, primaryRecommendation} from '../src/lib/audit/measurement-coverage';
import {buildDefaultAdvisorSteps} from '../src/lib/audit/llm-enrich';
import type {AuditReport} from '../src/lib/audit/types';
const source=process.env.AUDIT_QA_REPORT!;
const report:AuditReport=JSON.parse(readFileSync(source,'utf8')).result.report;
const original=structuredClone(report);
const ps=report.auditMeta!.pageSpeed! as import('../src/lib/audit/probes/pagespeed').PageSpeedResult;
assert(ps.rawError);
assert.deepEqual(pageSpeedDeficits(ps),[]);
assert.deepEqual(pageSpeedDeficits({...ps,configured:false}),[]);
assert(pageSpeedDeficits({...ps,rawError:undefined,configured:true,performanceScore:25}).some(d=>d.severity==='critical'));
const site=report.siteReview!;
const coverage=measurementCoverage(report,site);
assert(coverage.some(x=>x.includes('PageSpeed')));
assert(coverage.some(x=>x.includes('Bounded')));
assert(!coverage.some(x=>x.includes('page checks unavailable')));
assert(measurementCoverage(report,{...site,coverage:{...site.coverage,inspected:7}}).some(x=>x.includes('page checks unavailable')));
assert(measurementCoverage(report,{...site,coverage:{...site.coverage,inspected:0}}).includes('Multi-page website inspection'));
report.deficits=report.deficits.filter(d=>!d.finding.startsWith('PageSpeed measurement failed:') && d.finding!=='Mobile performance was not measured in this scan.');
report.coverage={status:'partial',missing:[...report.coverage!.missing.filter(x=>x!=='Some sampled website pages'),...coverage]};
report.packages.primary={...report.packages.primary,...primaryRecommendation(report.deficits)};
report.advisorSteps=buildDefaultAdvisorSteps(report);
assert.equal(report.packages.primary.headline,'Visibility & Measurement Review');
assert(!JSON.stringify([report.deficits,report.packages,report.advisorSteps]).includes('PageSpeed measurement failed'));
const changed=Object.keys(report).filter(k=>JSON.stringify(report[k as keyof AuditReport])!==JSON.stringify(original[k as keyof AuditReport]));
assert.deepEqual(changed.sort(),['advisorSteps','coverage','deficits','packages']);
if(process.env.AUDIT_REPAIR_OUTPUT)writeFileSync(process.env.AUDIT_REPAIR_OUTPUT,JSON.stringify(report,null,2),{mode:0o600});
console.log('PASS offline retained-evidence repair: timeout/config gaps, measured defect, bounded/error/no-page coverage, recommendations; only four derived fields changed');
