import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { NextRequest } from 'next/server';
import { emptyDiscovery, type DiscoveryState } from '../src/lib/hire/types';
import { buildHireEstimate, applyHireEstimate } from '../src/lib/hire/estimates';
import { applyUserControls, canProduceBrief, discoverySummary } from '../src/lib/hire/discovery-policy';
import { proposalFallback } from '../src/lib/hire/prompt';
import { parseModelTurn, runHireChatTurn } from '../src/lib/hire/openai';
import { extractWeeklyHours, runSalesTurn } from '../src/lib/hire/sales-engine';
import { createHireSession, getHireSession, updateHireSession, publicHireView } from '../src/lib/hire/sessions';
import { POST as chat } from '../src/app/api/hire/chat/route';
import { POST as finish, GET as get } from '../src/app/api/hire/[id]/route';
const d:DiscoveryState={...emptyDiscovery(),businessType:'Roofing',activePainId:'pain1',pains:[{id:'pain1',title:'Estimate follow-up',rawDescription:'I copy sent estimates into a sheet and chase replies by email each Friday.',tools:['Email','Spreadsheet'],processSteps:['Send estimate','Copy to spreadsheet','Chase reply'],whoDoesIt:'Owner',whyItHurts:'Takes up evenings',time:{label:'Follow-up',minutesPerOccurrence:null,occurrencesPerWeek:null,hiddenMinutesPerOccurrence:null,computedHoursPerWeek:null,statedHoursPerWeek:10,underestimationNote:null},automatable:true,confidence:0.8}]};
let groups=0; const pass=(s:string)=>{groups++;console.log('PASS',s);};
async function main(){
  assert(canProduceBrief(d));assert(!canProduceBrief(emptyDiscovery()));assert.equal(discoverySummary(d)[0].value,'Estimate follow-up');
  assert.deepEqual(buildHireEstimate(d).weekly,{low:7,high:9});
  for(const hours of [null,-2,169,NaN,Infinity])assert.equal(buildHireEstimate({...d,pains:[{...d.pains[0],time:{...d.pains[0].time,statedHoursPerWeek:hours}}]}).weekly,null);
  for(const automatable of [false,null])assert.equal(buildHireEstimate({...d,pains:[{...d.pains[0],automatable}]}).weekly,null);
  const invalid=structuredClone(d);invalid.pains[0].time.computedHoursPerWeek=9999;assert.equal(buildHireEstimate(invalid).weekly,null);
  const zero=structuredClone(d);zero.pains[0].time.statedHoursPerWeek=0;assert.equal(buildHireEstimate(zero).weekly,null);
  const tiny=structuredClone(d);tiny.pains[0].time.statedHoursPerWeek=.5;assert.deepEqual(buildHireEstimate(tiny).weekly,{low:.4,high:.5});
  assert.deepEqual(proposalFallback(emptyDiscovery()).hoursSavedPerWeek,{low:0,high:0});assert.equal(applyHireEstimate(proposalFallback(d),d).estimate?.basis,'247ROI benchmark for suitable repetitive work');
  pass('grounded benchmark, unknown/negative/invalid/tiny hours and noneligible work');
  assert.equal(extractWeeklyHours('2 hours a day'),null);assert.equal(extractWeeklyHours('2 hours per day, 3 days per week'),6);assert.equal(extractWeeklyHours('90 minutes/week'),1.5);assert.equal(extractWeeklyHours('8 hours per month'),null);
  assert.equal(proposalFallback({...d,pains:[{...d.pains[0],automatable:false}]}).recommendationKind,'keep_human');
  assert.equal(proposalFallback({...d,pains:[{...d.pains[0],time:{...d.pains[0].time,statedHoursPerWeek:2}}]}).recommendationKind,'existing_tools');
  const sensitive=structuredClone(d);sensitive.pains[0].title='Diagnosing patients';sensitive.pains[0].processSteps=['Examine patient','Choose treatment'];
  assert.equal(buildHireEstimate(sensitive).weekly,null);assert.equal(proposalFallback(sensitive).recommendationKind,'keep_human');
  assert.equal(applyUserControls(emptyDiscovery(),sensitive,'Please automate it').pains[0].automatable,false);
  const declined=applyUserControls(d,d,'I do not know the hours. Show my plan.');assert.equal(buildHireEstimate(declined).weekly,null);assert(declined.notes.includes('hours_unknown'));
  pass('daily/monthly ambiguity, unknown-hours control, clinical guard and no-build recommendations');
  const turn=parseModelTurn({reply:'Who handles that today?',phase:'process',discovery:d,readyForGate:false,choices:[{id:'me',label:'Mostly me',value:'I handle this myself.'}],inputMode:'both'},d);
  assert.equal(turn?.choices?.[0].id,'me');assert.equal(parseModelTurn({reply:'Fake advice',discovery:{pains:['bad']}},d),null);
  const correction=structuredClone(d);correction.pains[0].time.statedHoursPerWeek=null;correction.pains[0].time.computedHoursPerWeek=null;correction.notes=['hours_unknown'];
  const corrected=parseModelTurn({reply:'Not estimated.',phase:'time_verify',discovery:correction},d);assert.equal(corrected?.discovery?.pains[0].time.statedHoursPerWeek,null);
  pass('schema failures do not display unsaved facts; correction nulls survive');
  let discovery=emptyDiscovery();const transcript=[];for(const content of ['Roofing','Following up on quotes','I open Excel then copy sent estimates then send follow-up emails.','10 hours/week','More time with family']){transcript.push({role:'user' as const,content});const t=runSalesTurn(discovery,transcript);discovery=t.discovery!;transcript.push({role:'assistant' as const,content:t.reply});}
  assert(canProduceBrief(discovery));assert.equal(runSalesTurn(discovery,transcript).readyForGate,true);assert(discovery.notes.some(n=>n.startsWith('impact:')));assert.deepEqual(buildHireEstimate(discovery).weekly,{low:7,high:9});
  const rich=runSalesTurn(emptyDiscovery(),[{role:'user',content:'I run a roofing business. I open Excel then copy quotes then send emails, 10 hours/week.'}]);assert(canProduceBrief(rich.discovery!));assert.equal(rich.phase,'pain2_probe');
  pass('five-answer guided journey; rich answers skip redundant discovery');
  const fetchReal=globalThis.fetch;const key=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='test-only';globalThis.fetch=async()=>new Response('unavailable',{status:503});
  const fallback=await runHireChatTurn({discovery:emptyDiscovery(),messages:[{role:'user',content:'Plumbing'}]});assert.equal(fallback.mode,'guided');
  globalThis.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:'{not-json'}}]}),{status:200});assert.equal((await runHireChatTurn({discovery:emptyDiscovery(),messages:[]})).mode,'guided');globalThis.fetch=fetchReal;
  if(key)process.env.OPENAI_API_KEY=key;else delete process.env.OPENAI_API_KEY;
  pass('provider outage and malformed model response have functional fallback');
  for(const k of ['NEXT_PUBLIC_SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','SUPABASE_SECRET_KEY','SUPABASE_SERVICE_KEY','OPENAI_API_KEY','OPENAI_KEY'])delete process.env[k];
  delete process.env.HIRE_LOCAL_MEMORY;await assert.rejects(()=>createHireSession(),/unavailable/);process.env.HIRE_LOCAL_MEMORY='1';
  const s=await createHireSession({source:'qa_unit'});const payload={sessionId:s.id,message:'Roofing',requestId:randomUUID(),revision:s.updated_at};
  const req=(b:unknown)=>new Request('http://localhost/api/hire/chat',{method:'POST',body:JSON.stringify(b)});
  const first=await chat(req(payload));assert.equal(first.status,200);const data=await first.json();const replay=await chat(req(payload));assert.equal(replay.status,200);assert.equal((await replay.json()).replayed,true);assert.equal((await getHireSession(s.id))?.messages.length,2);
  assert.equal((await chat(req({...payload,requestId:randomUUID()}))).status,409);
  assert.equal((await chat(req({...payload,message:'x'.repeat(2001)}))).status,400);
  assert.equal((await chat(req({...payload,sessionId:'../../secret'}))).status,400);
  assert(data.revision!==s.updated_at);pass('fail-closed storage, idempotent retry, stale revision and request validation');
  const seeded=await updateHireSession(s.id,{discovery:d,proposal:proposalFallback(d),status:'gate_ready',first_name:'PRIVATE QA',email:'private@example.test',phone:'+15555550123'});
  assert(seeded);const pub=publicHireView(seeded);assert(!('email' in pub));assert(!('phone' in pub));assert(!('first_name' in pub));assert.equal(pub.messages.length,0);
  const params={params:Promise.resolve({id:s.id})};
  const forged=await finish(new NextRequest(`http://localhost/api/hire/${s.id}`,{method:'POST',body:JSON.stringify({confirmed:true,revision:seeded.updated_at,proposal:{employeeName:'FORGED'}})}),params);assert.equal(forged.status,200);
  const read=await get(new NextRequest(`http://localhost/api/hire/${s.id}`),params);assert.equal(read.headers.get('cache-control'),'private, no-store');const saved=await read.json();assert(saved.unlocked);assert.notEqual(saved.session.proposal.employeeName,'FORGED');assert(!JSON.stringify(saved).includes('private@example.test'));
  pass('ungated finalization uses server facts; contact fields never returned');
  const before=await getHireSession(s.id);assert(before);assert.equal(await updateHireSession(s.id,{phase:'ready'},'stale'),null);assert.equal((await getHireSession(s.id))?.updated_at,before.updated_at);
  process.env.VERCEL='1';await assert.rejects(()=>createHireSession(),/unavailable/);delete process.env.VERCEL;
  pass('optimistic storage revision and production cannot enable volatile fallback');
  console.log(JSON.stringify({passedGroups:groups}));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
