import assert from 'node:assert/strict';
import { inferServiceContext } from '../src/lib/audit/service-context';
const roof = inferServiceContext('Acme', { title:'Roofing and roof replacement in Richmond', metaDescription:'Local roofing services' });
assert.equal(roof.source, 'website'); assert.equal(roof.servicePhrase, 'roofer');
const ai = inferServiceContext('Acme', { title:'Custom AI employees and workflow automation for small businesses' });
assert.equal(ai.servicePhrase, 'AI business automation consultant'); assert.equal(ai.source, 'website');
assert.equal(inferServiceContext('Acme', {title:'Home - Acme'}).source, 'unconfirmed');
assert.equal(inferServiceContext('Jones Plumbing', {}).source, 'business_name');
assert.equal(inferServiceContext('Friendly Dentistry', {}).servicePhrase, 'dentist');
assert.equal(inferServiceContext('Friendly Dentistry', {}).source, 'business_name');
assert.equal(inferServiceContext('Acme', {title:'Mold removal and remediation'}).servicePhrase, 'mold remediation company');
assert.equal(inferServiceContext('Acme', {title:'Acme Dental Care'}).servicePhrase, 'dentist');
console.log('PASS: public-website service classification; unknown names remain unconfirmed, no private-data dependency.');
